### ISSUE TITLE
Explain what MSMB is -

### ISSUE THREAD

**Issue by LathaSrinivasan** [HewlettPackard/oneview-sdk-java#1]
Explain what MSMB is before using the acronym.

**Comment by filipe-kovalski** [comment]
Hi Latha, we recently released the 2.0 version of the SDK. Could you review or give us more details about this issue? Thanks!

**Comment by dzheltuk** [comment]
Hi Filipe, could you please describe the preconditions to run ScmbClient.java from samples.
I have changed SampleConstants with HP One View server data, and EnclosureClientSample is able to get all information.

I also run rabbit mq on my server. 

Is there any more requirements to run this code? Is that described in the documentation? At this moment I see:
2016-05-05 06:08:58 INFO  MessagingCertificateManager:108 - SCMBCertificatesImpl : getCACertificate : End
2016-05-05 06:09:00 ERROR ScmbConnectionManager:80 - ScmbConnectionManager : startScmb: IOException
ScmbClient : scmbProcessor : scmb connection not found

**Comment by lhsvobodaj** [comment]
Hi @dzheltuk 

About your issue using the ScmbClient, have you executed the steps described in [Fetch the SSL client certificates for RabbitMQ using a REST client](https://github.com/HewlettPackard/oneview-sdk-java#fetch-the-ssl-client-certificates-for-rabbitmq-using-a-rest-client) and [Generate KeyStore](https://github.com/HewlettPackard/oneview-sdk-java#generate-keystore)? Once you have successfully executed both steps and correctly updated the `SamplesConstants` with the path to you `KeyStore` and `TrustStore` files, their respective password and your OneView host and credentials, you should be able to run the `ScmbClient` sample.

Please, let me know the results. Thanks

**Comment by dzheltuk** [comment]
Hi Luiz, yes I have generated both certificates using such steps and tried to run ScmbClient - my result in the post above :( 
I'm able to get any configuration data using my SampleConstants. But for msmb and scmb I have the error.

Thank you for your help!

**Comment by lhsvobodaj** [comment]
Hi @dzheltuk 

Can you run the SDK doing a small change in the method `com.hp.ov.sdk.messaging.scmb.services.ScmbConnectionManager#startScmb`? I would ask you to include a `e.printStackTrace()` inside the catch block (you can add it at line 81). Unfortunately the exception threw inside this block is suppressing the original exception (`IOException`). In the meantime I will try to write a small test so we can check the connection to your RabbitMQ instance.

**Comment by dzheltuk** [comment]
Hi @lhsvobodaj 

Seems it's connect issue.

``` java
2016-05-11 09:53:53 ERROR ScmbConnectionManager:80 - ScmbConnectionManager : startScmb: IOException
java.net.SocketTimeoutException: connect timed out
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
    at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32)
    at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:34)
    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:83)
    at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:609)
    at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:639)
    at com.hp.ov.sdk.messaging.scmb.services.ScmbConnectionManager.startScmb(ScmbConnectionManager.java:76)
    at com.hp.ov.sdk.scmb.consumer.ScmbClient.scmbProcessor(ScmbClient.java:58)
    at com.hp.ov.sdk.scmb.consumer.ScmbClient.main(ScmbClient.java:104)
ScmbClient : scmbProcessor : scmb connection not found 
```

KeyStore/TrsustStore configured properly (I'm able to run other samples).
Can it be some kind of firewall issue or something like that?

**Comment by lhsvobodaj** [comment]
It could be. Can you try to execute a network connectivity test? Just try to establish a telnet connection to your RabbitMQ server address using port 5671 (`telnet ip_address 5671`). If telnet successfully connect to the server, the output should be something like this:

``` bash
Trying 172.16.102.174...
Connected to 172.16.102.174.
Escape character is '^]'.
```

If it does not work, you can check the RabbitMQ configuration file which should be located at `/ci/pre-ha-data/messaging/rabbitmq.config` in your OneView appliance machine. This file should contain an entry like `{ssl_listeners, [5671]}`.

Let me know the results.

**Comment by lhsvobodaj** [comment]
@dzheltuk any update on this issue?

**Comment by dzheltuk** [comment]
@lhsvobodaj yes, 
Thanks for the help! HpOneView is running on another network, so I'm able to get enclosures or any other elements, but not able to telnet to the server where Hp client is running on (ssh is available btw)

Is there any workaround available to run my scmb tests from another network? Some kind of tunnel maybe? Or it supposed to be run from the same network?

**Comment by lhsvobodaj** [comment]
The only requirement to run the `ScmbClient.java` is to have access to the RabbitMQ service running on the OneView host machine. 

About using a tunnel, it is possible to use this alternative. To do that you can create a SSH tunnel like `ssh username@oneview_host -L 2222:oneview_host:5671 -N`. This command will create a SSH tunnel binding the port _2222_ of you local machine to _oneview_host:5671_ (I am assuming you RabbitMQ is running on this port). One you have established the tunnel, you can set in your `hostname` and `amqpPort` as _localhost_ and _2222_ respectively (fields of `RestParams`).

I made a quick test here using this configuration and the SCMB client ran as expected.

**Comment by lhsvobodaj** [comment]
Hi @LathaSrinivasan 

Your comment about explaining what is MSMB before mentioning the acronym still applies to the current SDK documentation?

**Comment by lhsvobodaj** [comment]
@dzheltuk, have you tried to execute the ScmbClient using a SSH tunnel? It would be important for us to have your feedback about this usage scenario.

**Comment by lhsvobodaj** [comment]
1. @dzheltuk, did you execute the test using a [SSH tunnel](https://github.com/HewlettPackard/oneview-sdk-java/issues/1#issuecomment-220586510)?
2. @LathaSrinivasan, any feedback?

**Comment by dzheltuk** [comment]
@lhsvobodaj , sorry was on the vacation and was unable to check.

In my case HP One View is a virtual appliance running in VMWare. And ssh connection dies after password typing,

administrator@10.90.43.115's password:
Last login: Thu May 25 09:17:59 2016 from 192.168.204.101
CLI access is not supported.
Connection to 10.90.43.115 closed.

But I do not know if there is any cli connection available to appliance. Trying to check documents,

**Comment by lhsvobodaj** [comment]
@dzheltuk 

In the latest SDK release (3.0.0) we made some improvements in the message bus interfaces. I would recommend you to update the SDK version and start using the 3.0.0 in your project. If you still find any issues, please contact us so we can provide you support. 

Thanks
