### ISSUE TITLE
Connect to a version higher than 2.0 

### ISSUE THREAD

**Issue by nmateti** [HewlettPackard/oneview-sdk-java#10]
Wanted to use this library to connect with API Version higher than 2.0. Basically 3.0. But the code is not allowing that.

**Comment by lhsvobodaj** [comment]
Hi @nmateti 

The current version of the SDK does not support API Version 300+. However, you can still connect to an OneView 3.0 using API version 2.0 (200). We are already working on the API 300 support and soon a new version of the SDK will be publically available. Besides the support for API 300, this new release contains some improvements in terms of design and performance.

**Comment by CintiaLopes** [comment]
Hi @nmateti,

Since v3.0.0 released in October 2016, SDK supports API 300.

**Comment by CintiaLopes** [comment]
Closing since API300 is supported since v3.0.0.
