### ISSUE TITLE
Question: How much connections can be created using SDK

### ISSUE THREAD

**Issue by dzheltuk** [HewlettPackard/oneview-sdk-java#13]
Hello!

Do you have any documented information regarding how much scmb connections can be created to Hp One View server using your sdk. Is that limited? Possibly I will need to create about 10-15 different connections (to get info for each blade separately)

Regards,

Dmitriy

**Comment by lhsvobodaj** [comment]
Currently, the SDK does not have a limit regarding the number of SCMB connections that can be established with OneView. Considering your use case, I believe you should not have problems creating 10-15 connections. In case you have any issues while creating and using these connections, feel free to contact us.

Thanks
