### ISSUE TITLE
Need to add API to load active alarms only

### ISSUE THREAD

**Issue by dzheltuk** [HewlettPackard/oneview-sdk-java#14]
Hello,

Trying to use sdk with 3.1.0 version. And I see that there are no any possibility to load active alarms only (we have about 10k old alartms in the system - so it took really long time to load all of them)
Is there any chance to add such useful method to the API.

![image](https://user-images.githubusercontent.com/10085878/28072176-e724f23e-665a-11e7-9062-744e45a42051.png)

client.getAllActive() for example

Thank you!

**Comment by dzheltuk** [comment]
@lhsvobodaj any good new on that? :)

**Comment by lhsvobodaj** [comment]
Hi @dzheltuk 

About your comment regarding the support for a utility method on the alerts client to retrieve only the active alarms. Currently, the SDK already supports this type of filtering through the `URIQuery` param on the `get()` method. Below is a code snippet that illustrates how you can create and use the filter:
```java
BasicURIQuery filterByActive = new BasicURIQuery();

filterByActive.addParameter(URIQuery.FILTER, "alertState='Active'");

ResourceCollection<AlertResource> alertResources = this.alertsClient.get(filterByActive);
```
Does this approach work for you?

**Comment by dzheltuk** [comment]
Thanks a lot! That helped!
