### ISSUE TITLE
authLoginDomain should not be "Local" by default

### ISSUE THREAD

**Issue by nmateti** [HewlettPackard/oneview-sdk-java#39]
### Scenario/Intent

While establishing a connection to OneView , the login domain should not be Local by default. It should be set to an empty string. That way the default domain will be whatever is configured in OneView.
---
#### Steps to Reproduce

Set the default directory in OneView to something other than Local.
Log in using the SDK with a user associated with the above directory and do not send a login domain field.
The API should allow to log in. 

#### Actual Result

---
#### Environment Details
 - **OneView Java SDK:** 
    <Version of the oneview-sdk-java module for which you are encountering the issue>
3.1.2
 - **OneView Appliance Version:** 
    <Version of the OneView appliance you are interacting with>
 - **OneView Client API Version:** 
    <OnewView API version listed in your configuration file>
 - **Java Version:** 
    <Version of Java in your environment>
 - **Platform:** 
    <OS distribution and release version>

---

**Comment by soodpr** [comment]
Hi @nmateti,
Can you please elaborate more on this because as per my observation, its configurable in the properties file.

**Comment by soodpr** [comment]
After doing initial investigation, we are not supporting OneView LoginDomains Global settings resource to get the default domain from OneView. That's why we are setting default value to Local in case user does not configure domain in the properties file.
