### ISSUE TITLE
Retrieve active alerts information using SDK

### ISSUE THREAD

**Issue by dzheltuk** [HewlettPackard/oneview-sdk-java#5]
Hello,
When I checked SDK functionality I recognized that alertrequest (http://h17007.www1.hpe.com/docs/enterprise/servers/oneview2.0/cic-api/en/api-docs/current/index.html#rest/alerts) is not added for some reason. Are you able to add that - or there is another way to get all active alarms information using SDK?

Regards,
Dmitriy

**Comment by lhsvobodaj** [comment]
Hi @dzheltuk 

Indeed, there is no client to access the Alerts REST API yet. We should include support for this API in a near future release. One alternative, while we still does not have this client available, would be to create an [SCMB consumer](http://h17007.www1.hpe.com/docs/enterprise/servers/oneview2.0/cic-rest/en/content/s_using-SCMB-ci.html) using `scmb.alerts.#` as routing key. The cited documentation contains detailed instructions about how to create the consumer and establish a connection to the State-Change Message Bus.

You can also take a look at the file [ScmbClient.java](https://github.com/HewlettPackard/oneview-sdk-java/blob/v2.0.0/samples/src/main/java/com/hp/ov/sdk/scmb/consumer/ScmbClient.java). In this example we create a consumer to listen to task resource changes.

Feel free to contact us in case you have any doubt or issue while using the SCMB. Also, it would be great if you could share your results using this feature.

**Comment by lhsvobodaj** [comment]
@dzheltuk 

Release 3.0.0 contains a client for Alerts REST API (`AlertClient.java`). Besides, we have also improved the interface to connect to both message buses (Metric Streaming and State-Changed).
